import React, { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

const API = 'http://localhost:5000/api';
const defaultInputs = { tvd:2500, wob:20, rpm:120, bitDiameter:8.5, formationStrength:40, mudWeight:1.2, annularPressureLoss:18, torque:8, bitWear:10, maxEcd:1.50, maxMse:2000 };
const emptyResult = { rop:0, hydrostaticPressureBar:0, ecd:0, mseMpa:0, bitEfficiencyPercent:0, drillingEfficiencyPercent:0, interpretation:[] };

function ChartBox({ title, data, dataKey, type='line', xLabel, yLabel }) {
  return <div className="card chart-card"><h3>{title}</h3>{data?.length ? <ResponsiveContainer width="100%" height={280}>{type==='bar' ? <BarChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="parameter"/><YAxis label={{value:yLabel, angle:-90, position:'insideLeft'}}/><Tooltip/><Bar dataKey={dataKey}/></BarChart> : <LineChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="parameter" label={{value:xLabel, position:'insideBottom', offset:-5}}/><YAxis label={{value:yLabel, angle:-90, position:'insideLeft'}}/><Tooltip/><Line type="monotone" dataKey={dataKey} strokeWidth={2}/></LineChart>}</ResponsiveContainer> : <div className="no-data">No chart data available.</div>}</div>;
}

export default function App(){
  const [inputs,setInputs]=useState(defaultInputs); const [result,setResult]=useState(emptyResult); const [sens,setSens]=useState(null); const [opt,setOpt]=useState(null); const [history,setHistory]=useState([]); const [tab,setTab]=useState('dashboard'); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem('drillingAnalysisHistory')||'[]'))}catch{setHistory([])}},[]);
  const update=(k,v)=>setInputs(p=>({...p,[k]:Number(v)}));
  const saveEntry=(r,o)=>{const entry={id:Date.now(),date:new Date().toLocaleString(),inputs:{...inputs},result:r,optimization:o};const next=[entry,...history].slice(0,20);setHistory(next);localStorage.setItem('drillingAnalysisHistory',JSON.stringify(next));};
  const analyze=async(save=true)=>{setLoading(true);setError('');try{const [a,s,o]=await Promise.all([axios.post(`${API}/analyze`,inputs),axios.post(`${API}/sensitivity`,inputs),axios.post(`${API}/optimize`,{input:inputs,ranges:{wobMin:10,wobMax:30,wobStep:2,rpmMin:80,rpmMax:160,rpmStep:10}})]);setResult(a.data);setSens(s.data);setOpt(o.data);if(save)saveEntry(a.data,o.data);return a.data}catch(e){setError(e.response?.data?.message||'Could not connect to the analysis server. Start the backend first.');throw e}finally{setLoading(false)}};
  const reset=()=>{setInputs(defaultInputs);setResult(emptyResult);setSens(null);setOpt(null);setError('');};
  const remove=id=>{const next=history.filter(x=>x.id!==id);setHistory(next);localStorage.setItem('drillingAnalysisHistory',JSON.stringify(next));};
  const clear=()=>{setHistory([]);localStorage.removeItem('drillingAnalysisHistory');};
  const feasible=useMemo(()=>opt?.feasiblePoints||[],[opt]);

  return <div className="app"><header><div><h1>Drilling Parameter Optimization</h1><p>WOB, RPM, ROP, MSE and ECD analysis</p></div></header>
  <nav>{[['dashboard','Dashboard'],['sensitivity','Sensitivity'],['optimization','Optimization'],['history','History']].map(([k,t])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{t}</button>)}</nav>
  <main>{error&&<div className="error">{error}</div>}
    <section className="card input-card"><h2>Drilling Inputs</h2><div className="input-grid">{[['tvd','TVD (m)'],['wob','WOB (kN)'],['rpm','RPM'],['bitDiameter','Bit Diameter (in)'],['formationStrength','Formation Strength (MPa)'],['mudWeight','Mud Weight (g/cc)'],['annularPressureLoss','Annular Pressure Loss (bar)'],['torque','Torque (kN-m)'],['bitWear','Bit Wear (%)'],['maxEcd','Max ECD (g/cc)'],['maxMse','Max MSE (MPa)']].map(([k,l])=><label key={k}>{l}<input type="number" value={inputs[k]} step={k==='bitDiameter'||k==='mudWeight'||k==='maxEcd'?'0.01':'1'} onChange={e=>update(k,e.target.value)}/></label>)}</div><div className="actions"><button onClick={()=>analyze(true)} disabled={loading}>{loading?'Running...':'Run Analysis & Save'}</button><button className="secondary" onClick={()=>{reset();}}>Reset</button></div></section>

    {tab==='dashboard'&&<><section className="metrics">{[['ROP',result.rop,'m/hr'],['Hydrostatic Pressure',result.hydrostaticPressureBar,'bar'],['ECD',result.ecd,'g/cc'],['MSE',result.mseMpa,'MPa'],['Bit Efficiency',result.bitEfficiencyPercent,'%'],['Comparative Efficiency',result.drillingEfficiencyPercent,'%']].map(([a,b,c])=><div className="metric" key={a}><span>{a}</span><strong>{b} {c}</strong></div>)}</section>
      <section className="grid2"><ChartBox title="WOB vs ROP" data={sens?.wob} dataKey="rop" xLabel="WOB (kN)" yLabel="ROP (m/hr)"/><ChartBox title="RPM vs ROP" data={sens?.rpm} dataKey="rop" xLabel="RPM" yLabel="ROP (m/hr)"/><ChartBox title="WOB vs MSE" data={sens?.wobMse} dataKey="mse" type="bar" xLabel="WOB (kN)" yLabel="MSE (MPa)"/><ChartBox title="Torque vs MSE" data={sens?.torque} dataKey="mse" xLabel="Torque (kN-m)" yLabel="MSE (MPa)"/></section>
      <section className="card"><h2>Engineering Interpretation</h2><ul>{result.interpretation?.map((x,i)=><li key={i}>{x}</li>)}</ul><p className="note">The ROP equation is a simplified empirical model. MSE is calculated from WOB, torque, RPM, bit area and ROP using SI units. ECD uses the supplied annular pressure loss and mud weight.</p></section></>}

    {tab==='sensitivity'&&<section className="grid2"><ChartBox title="WOB vs ROP" data={sens?.wob} dataKey="rop" xLabel="WOB (kN)" yLabel="ROP (m/hr)"/><ChartBox title="RPM vs ROP" data={sens?.rpm} dataKey="rop" xLabel="RPM" yLabel="ROP (m/hr)"/><ChartBox title="WOB vs MSE" data={sens?.wobMse} dataKey="mse" type="bar" xLabel="WOB (kN)" yLabel="MSE (MPa)"/><ChartBox title="Torque vs MSE" data={sens?.torque} dataKey="mse" xLabel="Torque (kN-m)" yLabel="MSE (MPa)"/></section>}

    {tab==='optimization'&&<section className="card"><h2>Model Optimization</h2>{opt?.best?<><div className="best"><div><span>WOB</span><strong>{opt.best.wob} kN</strong></div><div><span>RPM</span><strong>{opt.best.rpm}</strong></div><div><span>Predicted ROP</span><strong>{opt.best.rop} m/hr</strong></div><div><span>MSE</span><strong>{opt.best.mse} MPa</strong></div><div><span>ECD</span><strong>{opt.best.ecd} g/cc</strong></div></div><p className="note">The search maximizes modeled ROP while satisfying the entered MSE and ECD limits. Because the current ECD equation uses mud weight, TVD and annular pressure loss, ECD does not vary directly with WOB/RPM in this simplified model.</p><h3>Feasible WOB/RPM combinations</h3><div className="table-wrap"><table><thead><tr><th>WOB (kN)</th><th>RPM</th><th>ROP (m/hr)</th><th>MSE (MPa)</th><th>ECD (g/cc)</th></tr></thead><tbody>{feasible.map((x,i)=><tr key={i}><td>{x.wob}</td><td>{x.rpm}</td><td>{x.rop}</td><td>{x.mse}</td><td>{x.ecd}</td></tr>)}</tbody></table></div></>:<p>Run the analysis to generate feasible operating combinations.</p>}</section>}

    {tab==='history'&&<section className="card"><div className="section-head"><div><h2>Analysis History</h2><p>Saved runs from this browser.</p></div>{history.length>0&&<button className="danger" onClick={clear}>Clear History</button>}</div>{history.length===0?<p>No saved analyses yet.</p>:<div className="table-wrap"><table><thead><tr><th>Date</th><th>WOB</th><th>RPM</th><th>ROP</th><th>MSE</th><th></th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td>{x.date}</td><td>{x.inputs.wob}</td><td>{x.inputs.rpm}</td><td>{x.result?.rop}</td><td>{x.result?.mseMpa}</td><td><button className="danger small" onClick={()=>remove(x.id)}>Delete</button></td></tr>)}</tbody></table></div>}</section>}
  </main><footer>DrillOpt | Drilling Parameter Analysis</footer></div>;
}
